-- ADDING PAYMENT STATUS TO ATTENDEES
ALTER TABLE public.event_attendees ADD COLUMN IF NOT EXISTS is_paid BOOLEAN DEFAULT FALSE;

-- ENSURE PROFILES HAS PHONE FOR WHATSAPP
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone TEXT;
